#redis test appication setting
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/redisTest
      
  redis:
    host: localhost
    port: 6379
    timeout: 6000
    password: null
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
    
    